"""add ai_questions_asked and max_ai_questions to lesson_creation_sessions

Revision ID: 7ee85c7e5fcc
Revises: e5676610fb03
Create Date: 2025-09-21 21:13:31.463682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ee85c7e5fcc'
down_revision = 'e5676610fb03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson_creation_sessions', sa.Column('ai_questions_asked', sa.Integer(), nullable=False, server_default='0', comment='已提问的问题数量'))
    op.add_column('lesson_creation_sessions', sa.Column('max_ai_questions', sa.Integer(), nullable=False, server_default='5', comment='最大问题数量'))
    # Backfill existing rows with default values (in case the DB does not do this automatically)
    op.execute("UPDATE lesson_creation_sessions SET ai_questions_asked = 0 WHERE ai_questions_asked IS NULL")
    op.execute("UPDATE lesson_creation_sessions SET max_ai_questions = 5 WHERE max_ai_questions IS NULL")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lesson_creation_sessions', 'max_ai_questions')
    op.drop_column('lesson_creation_sessions', 'ai_questions_asked')
    # ### end Alembic commands ###