"""initial migration

Revision ID: 9e8ea085bd3f
Revises: 
Create Date: 2025-09-24 04:14:23.302978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e8ea085bd3f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson_plans', sa.Column('web_search_info', sa.JSON(), nullable=True, comment='联网搜索结果信息'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lesson_plans', 'web_search_info')
    # ### end Alembic commands ###