"""initial_schema

Revision ID: c68683d8284e
Revises: 
Create Date: 2025-09-24 07:12:07.618830

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c68683d8284e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_analysis_reports_analysis_id', table_name='analysis_reports')
    op.drop_index('ix_analysis_reports_id', table_name='analysis_reports')
    op.drop_table('analysis_reports')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_reports',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='报告ID'),
    sa.Column('analysis_id', mysql.VARCHAR(length=36), nullable=True, comment='用于API交互的唯一ID'),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='上传该报告的用户ID'),
    sa.Column('summary', mysql.TEXT(), nullable=True, comment='AI生成的自然语言分析摘要'),
    sa.Column('charts_data', mysql.JSON(), nullable=True, comment='用于图表可视化的数据'),
    sa.Column('knowledge_gaps', mysql.JSON(), nullable=True, comment='识别出的知识点差距和教学建议'),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='analysis_reports_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    comment='学情分析报告表',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_comment='学情分析报告表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_analysis_reports_id', 'analysis_reports', ['id'], unique=False)
    op.create_index('ix_analysis_reports_analysis_id', 'analysis_reports', ['analysis_id'], unique=True)
    # ### end Alembic commands ###