"""Recreate analytics model

Revision ID: e1ba903ce39a
Revises: 
Create Date: 2025-09-24 21:05:53.591524

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e1ba903ce39a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.drop_index('ix_analysis_reports_analysis_id', table_name='analysis_reports')
        op.drop_index('ix_analysis_reports_id', table_name='analysis_reports')
        op.drop_table('analysis_reports')
    except Exception as e:
        print(f"Ignored error during drop: {e}")

    op.create_table('analysis_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='报告ID'),
    sa.Column('analysis_id', sa.String(length=36), nullable=True, comment='用于API交互的唯一ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='上传该报告的用户ID'),
    sa.Column('summary', sa.Text(), nullable=True, comment='AI生成的完整叙事性分析报告（Markdown格式）'),
    sa.Column('charts_data', mysql.JSON(), nullable=True, comment='[已废弃] 用于图表可视化的数据'),
    sa.Column('knowledge_gaps', mysql.JSON(), nullable=True, comment='[已废弃] 识别出的知识点差距和教学建议'),
    sa.Column('average_score', sa.String(length=10), nullable=True, comment='[已废弃] 班级平均分'),
    sa.Column('failing_students_count', sa.Integer(), nullable=True, comment='[已废弃] 不及格学生人数'),
    sa.Column('failing_students_list', mysql.JSON(), nullable=True, comment='[已废弃] 不及格学生名单'),
    sa.Column('knowledge_point_error_rates', mysql.JSON(), nullable=True, comment='[已废弃] 各知识点错误率'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='学情分析报告表'
    )
    op.create_index('ix_analysis_reports_id', 'analysis_reports', ['id'], unique=False)
    op.create_index('ix_analysis_reports_analysis_id', 'analysis_reports', ['analysis_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_analysis_reports_analysis_id', table_name='analysis_reports')
    op.drop_index('ix_analysis_reports_id', table_name='analysis_reports')
    op.drop_table('analysis_reports')
    # ### end Alembic commands ###