"""add history and lesson_plan_id to lesson_creation_sessions

Revision ID: e5676610fb03
Revises: 
Create Date: 2025-09-20 17:45:35.492503

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e5676610fb03'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_conversations_id', table_name='conversations')
    op.drop_table('conversations')
    op.add_column('lesson_creation_sessions', sa.Column('lesson_plan_id', sa.Integer(), nullable=True, comment='关联教案ID'))
    op.add_column('lesson_creation_sessions', sa.Column('history', sa.JSON(), nullable=False, comment='存储对话历史记录'))
    op.create_foreign_key(None, 'lesson_creation_sessions', 'lesson_plans', ['lesson_plan_id'], ['id'])
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_constraint(None, 'lesson_creation_sessions', type_='foreignkey')
    op.drop_column('lesson_creation_sessions', 'history')
    op.drop_column('lesson_creation_sessions', 'lesson_plan_id')
    op.create_table('conversations',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='会话ID'),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='用户ID'),
    sa.Column('history', mysql.JSON(), nullable=False, comment='存储对话历史 (例如: [{"role": "ai", "content": "..."}, {"role": "user", "content": "..."}])'),
    sa.Column('status', mysql.VARCHAR(length=50), nullable=True, comment='会话状态 (例如: in_progress, completed, failed)'),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('lesson_plan_id', mysql.INTEGER(), autoincrement=False, nullable=True, comment='如果会话成功生成教案，关联到教案ID'),
    sa.ForeignKeyConstraint(['lesson_plan_id'], ['lesson_plans.id'], name='conversations_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='conversations_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_conversations_id', 'conversations', ['id'], unique=False)
    # ### end Alembic commands ###